---
title: "Assignment: R Markdown and Plotly"
subtitle: "Coursera Course: Developing Data Products"
author: "Konstantinos"
date: "`r paste('December',format(Sys.Date(),'%d'),',',format(Sys.Date(),'%Y'))`"
output:
 prettydoc::html_pretty:
   df_print: paged
   fig_caption: yes
   highlight: vignette
   number_sections: yes
   theme: hpstr
   toc: yes
---
```{r setup, include=FALSE}
# default", "tango", "pygments", "kate", "monochrome", "espresso", "zenburn", "haddock", "textmate"
knitr::opts_chunk$set(tidy = FALSE)
options(htmltools.dir.version = FALSE,knitr.table.format = 'markdown')
```
```{r include=FALSE}
library(lubridate)
library(plotly)
library(dplyr)
library(knitr)
library(kableExtra)
library(titanic)
library(scales)
library(RColorBrewer)
Sys.setlocale("LC_ALL","English")
```


# Dataset
I just used the famous titanic dataset.
```{r}
titanic_train
```


# Plotly


```{r warning=FALSE}
titanic_train[titanic_train$Embarked=='',12] = NA
plot_ly(na.omit(titanic_train), x = ~ Age, y = ~Fare, color  = ~ as.factor(Embarked),mode='markers',type = 'scatter') 

```
